# Generated by Django 4.0 on 2021-12-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0007_remove_cart_total'),
        ('home', '0014_delete_contactinfo_contact_address_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Checkoutform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_By', models.CharField(max_length=200)),
                ('country', models.TextField()),
                ('address', models.TextField(default=0)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('items', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.item')),
            ],
        ),
    ]
