# Generated by Django 4.0 on 2021-12-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_totalcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalcart',
            old_name='carts',
            new_name='cart',
        ),
    ]
