# Generated by Django 4.0 on 2021-12-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slider_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
