# Generated by Django 4.0 on 2021-12-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
