# Generated by Django 4.0 on 2021-12-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contactinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
