# Generated by Django 4.0 on 2021-12-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_contactinfo_contact_address_contact_phone'),
        ('cart', '0002_alter_cart_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.item'),
        ),
    ]
